apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --out=k8s
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: llm-server
  name: llm-server
spec:
  ports:
    - name: "8002"
      port: 8002
      targetPort: 8002
  selector:
    io.kompose.service: llm-server
status:
  loadBalancer: {}
