apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    io.kompose.service: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: nginx
    spec:
      securityContext:
        runAsUser: 0  # Set the user ID (UID) to 0 for root
      initContainers:
        - name: download-config
          image: curlimages/curl
          command: ["sh", "-c", "curl -o /nginx-config/nginx.conf https://raw.githubusercontent.com/openchatai/OpenCopilot/feat/k8s/nginx/nginx_k8s.conf"]
          volumeMounts:
            - mountPath: /nginx-config
              name: nginx-config-volume
      containers:
        - image: nginx
          name: nginx
          ports:
            - containerPort: 80
              hostPort: 8888
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /etc/nginx
              name: nginx-config-volume
      restartPolicy: Always
      volumes:
        - name: nginx-config-volume
          emptyDir: {}
