apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out=k8s
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: qdrant
  name: qdrant
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: qdrant
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --out=k8s
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/opencopilot-opencopilot-network: "true"
        io.kompose.service: qdrant
    spec:
      containers:
        - image: qdrant/qdrant
          name: qdrant
          ports:
            - containerPort: 6333
              hostPort: 6333
              protocol: TCP
            - containerPort: 6334
              hostPort: 6334
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /qdrant/storage
              name: qdrant-storage
      restartPolicy: Always
      volumes:
        - name: qdrant-storage
          persistentVolumeClaim:
            claimName: qdrant-storage
status: {}
