apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --out=k8s
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: selenium
  name: selenium
spec:
  ports:
    - name: "4444"
      port: 4444
      targetPort: 4444
    - name: "7900"
      port: 7900
      targetPort: 7900
  selector:
    io.kompose.service: selenium
status:
  loadBalancer: {}
